### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by p0m3e3** [onyxdevs/react-slot-machine#1]
/home/kali/booking_test/src/stores/cart/sagas.ts
TypeScript error in /home/kali/booking_test/src/stores/cart/sagas.ts(29,37):
Object is of type 'unknown'.  TS2571

    27 |         yield put(applyCoupon(resData[0]));
    28 |     } catch (error) {
  > 29 |         yield put(applyCouponFailed(error.message));
       |                                     ^
    30 |     }
    31 | }
    32 |

**Comment by onyxdevs** [comment]
Hello,
You have to navigate in the Terminal to the project's directory and then run: npm install
Then run: npm start

**Comment by onyxdevs** [comment]
Hello,
Could you provide more information?
I think you've posted the issue on the wrong repository.
This is the correct repository:
https://github.com/onyxdevs/react-hotel-reservation-system/
